In [4]:
API_KEY = "AIzaSyA1SLSrQuMk74VCC--Nz8ACjBdTJirIej8"

In [5]:
from urllib.parse import urlencode
import googlemaps
import pandas
import requests

In [6]:
dataType = "json"
endpoint = f"https://maps.googleapis.com/maps/api/geocode/{dataType}"
parameters = {"address": "1600 Amphitheatre Parkway, Mountain View, CA", "key": API_KEY}
urlParameters = urlencode(parameters)
sample = "https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY"
print(urlParameters)

url = f"{endpoint}?{urlParameters}"
print(url)

address=1600+Amphitheatre+Parkway%2C+Mountain+View%2C+CA&key=AIzaSyA1SLSrQuMk74VCC--Nz8ACjBdTJirIej8
https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway%2C+Mountain+View%2C+CA&key=AIzaSyA1SLSrQuMk74VCC--Nz8ACjBdTJirIej8


In [7]:
def extractLatLong(location, dataType = "json"):
    endpoint = f"https://maps.googleapis.com/maps/api/geocode/{dataType}"
    parameters = {"address": location, "key": API_KEY}
    urlParameters = urlencode(parameters)
    url = f"{endpoint}?{urlParameters}"
    r = requests.get(url)
    if r.status_code not in range(200, 299):
        return {}
    latlng = {}
    try:
        latlng = r.json()["results"][0]["geometry"]["location"]
    except:
        pass
    return latlng.get("lat"), latlng.get("lng")

In [8]:
extractLatLong("1600 Amphitheatre Parkway, Mountain View, CA")

(37.4223878, -122.0841877)

In [9]:
from googlemaps import distance_matrix as distanceMatrix

Distance matrix has 3 necessary parameters: client, origin, and destinations. Origin would be the agent's address, and destinations would be the list of service locations.

Origin Type is a single location
Destination Type is a list of locations

Distance matrix should automatically use geocode into lattitude and longitude, but using geocode ourselves before sending to distance matrix leaves less debugging later on

Parameter: Language: use english initially then change according to agent needs (we can either use google translate via the distance matrix API or we can use google translate ourselves)
Parameter: Mode: Initally set it to driving, and if agent needs to use some other means of transport, we can parse that here
Parameter: Avoid:  We can use avoid later for the googlemap functions avoid tolls, highways etc.
Parameter: Units: Initially leave it to imperial, then later we can change it to metric depending on the agent needss
Parameter: Departure Time: we will set it to 8:30 or 9AM initially. Later when we add multiple times of day, we can set it to the appropriate afternoon/evening times
Parameter: Arrival Time: Initally we should not have this, but if necessary we can implement in case customer has special cases

In [10]:
plmsLoc = extractLatLong("3200 228th Ave SE, Sammamish, WA")
print(plmsLoc)
plms = "3200 228th Ave SE, Sammamish, WA"

(47.5802154, -122.0323862)


In [11]:
elementaryLoc = extractLatLong("3933 Jewell Rd, Bothell, WA")
elementary = "3933 Jewell Rd, Bothell, WA"
print(elementaryLoc)

(47.8205701, -122.1794354)


In [12]:
friendLoc = extractLatLong("1122 228th Ave SE, Sammamish, WA")
friend = "1122 228th Ave SE, Sammamish, WA"
print(friendLoc)

(47.6001135, -122.0323108)


In [13]:
from urllib.parse import urlencode
data_type = 'json'
params = {"origins" : friend, "destinations" : elementary, "key" : API_KEY}
urlParams = urlencode(params)
endpoint2 = f"https://maps.googleapis.com/maps/api/distancematrix/{data_type}"
url = f"{endpoint2}?{urlParams}"
print(url)

https://maps.googleapis.com/maps/api/distancematrix/json?origins=1122+228th+Ave+SE%2C+Sammamish%2C+WA&destinations=3933+Jewell+Rd%2C+Bothell%2C+WA&key=AIzaSyA1SLSrQuMk74VCC--Nz8ACjBdTJirIej8


In [14]:
import json
import urllib.request as request
import urllib.error
def extractMatrix(origins = None, destinations = None):
    data_type = 'json'
    params = {"origin_addresses" : origins, "destination_addresses" : destinations, "key" : API_KEY}
    urlParams = urlencode(params)
    endpoint2 = f"https://maps.googleapis.com/maps/api/distancematrix/{data_type}"
    url = f"{endpoint2}?{urlParams}"
    
    payload={}
    headers = {}

    response = requests.request("GET", url, headers=headers, data=payload)

    print(response.text)
    

In [15]:
locList = ["Lexington, MA, USA", "Concord, MA, USA"]
extractMatrix(locList, locList)

{
   "destination_addresses" : [],
   "origin_addresses" : [],
   "rows" : [],
   "status" : "INVALID_REQUEST"
}



In [16]:
import requests

url = f"https://maps.googleapis.com/maps/api/distancematrix/json?origins=849VCWC8%2BR9&destinations=San%20Francisco&key={API_KEY}"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

{
   "destination_addresses" : [ "San Francisco, CA, USA" ],
   "origin_addresses" : [ "CWC8+R9 Mountain View, CA, USA" ],
   "rows" : [
      {
         "elements" : [
            {
               "distance" : {
                  "text" : "56.9 km",
                  "value" : 56938
               },
               "duration" : {
                  "text" : "40 mins",
                  "value" : 2416
               },
               "status" : "OK"
            }
         ]
      }
   ],
   "status" : "OK"
}



In [17]:
import requests

url = f"https://maps.googleapis.com/maps/api/distancematrix/json?origins=40.6655101%2C-73.89188969999998&destinations=enc%3A_kjwFjtsbMt%60EgnKcqLcaOzkGari%40naPxhVg%7CJjjb%40cqLcaOzkGari%40naPxhV%3A&key={API_KEY}"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

{
   "destination_addresses" : [
      "339 Hicks St, Brooklyn, NY 11201, USA",
      "585 Schenectady Ave, Brooklyn, NY 11203, USA",
      "102-1 66th Rd, Queens, NY 11375, USA",
      "1000 N Village Ave, Rockville Centre, NY 11570, USA",
      "3-28 Beach 19th St, Queens, NY 11691, USA",
      "585 Schenectady Ave, Brooklyn, NY 11203, USA",
      "102-1 66th Rd, Queens, NY 11375, USA",
      "1000 N Village Ave, Rockville Centre, NY 11570, USA",
      "3-28 Beach 19th St, Queens, NY 11691, USA"
   ],
   "origin_addresses" : [ "P.O. Box 793, Brooklyn, NY 11207, USA" ],
   "rows" : [
      {
         "elements" : [
            {
               "distance" : {
                  "text" : "10.4 km",
                  "value" : 10448
               },
               "duration" : {
                  "text" : "36 mins",
                  "value" : 2141
               },
               "status" : "OK"
            },
            {
               "distance" : {
                  "text" : "4.7 k

In [18]:
import requests

url = f"https://maps.googleapis.com/maps/api/distancematrix/json?origins=849VCWC8%2BR9&destinations=San%20Francisco&key={API_KEY}"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

{
   "destination_addresses" : [ "San Francisco, CA, USA" ],
   "origin_addresses" : [ "CWC8+R9 Mountain View, CA, USA" ],
   "rows" : [
      {
         "elements" : [
            {
               "distance" : {
                  "text" : "56.9 km",
                  "value" : 56938
               },
               "duration" : {
                  "text" : "40 mins",
                  "value" : 2416
               },
               "status" : "OK"
            }
         ]
      }
   ],
   "status" : "OK"
}



In [19]:
import requests

url = f"https://maps.googleapis.com/maps/api/distancematrix/json?origins=Boston%2CMA%7CCharlestown%2CMA&destinations=Lexington%2CMA%7CConcord%2CMA&departure_time=now&key={API_KEY}"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

{
   "destination_addresses" : [ "Lexington, MA, USA", "Concord, MA, USA" ],
   "origin_addresses" : [ "Boston, MA, USA", "Charlestown, Boston, MA, USA" ],
   "rows" : [
      {
         "elements" : [
            {
               "distance" : {
                  "text" : "33.2 km",
                  "value" : 33249
               },
               "duration" : {
                  "text" : "27 mins",
                  "value" : 1619
               },
               "duration_in_traffic" : {
                  "text" : "25 mins",
                  "value" : 1487
               },
               "status" : "OK"
            },
            {
               "distance" : {
                  "text" : "31.6 km",
                  "value" : 31610
               },
               "duration" : {
                  "text" : "32 mins",
                  "value" : 1948
               },
               "duration_in_traffic" : {
                  "text" : "30 mins",
                  "value" : 1807
    

"+" is spacebar
"|" seperates each element in a list of locations 

In [20]:
address = "Lexington, MA, USA"
list1 = address.split(",")
string = "".join(f"{i}+" for i in list1)
string = (string[:-1]).replace(" ","")
print(string)

Lexington+MA+USA


In [21]:
addressList = [ "Lexington, MA, USA", "Concord, MA, USA" ]
queryList = ""
for addy in addressList:
    string = "".join(f"{i}+" for i in addy.split(","))
    string = (string[:-1]).replace(" ","")
    queryList += f"{string}|"
queryList = queryList[:-1]
print(queryList)

Lexington+MA+USA|Concord+MA+USA


In [22]:
url = f"https://maps.googleapis.com/maps/api/distancematrix/json?origins=Lexington+MA+USA|Concord+MA+USA&destinations=Lexington+MA+USA|Concord+MA+USA&departure_time=now&key={API_KEY}"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)


{
   "destination_addresses" : [ "Lexington, MA, USA", "Concord, MA, USA" ],
   "origin_addresses" : [ "Lexington, MA, USA", "Concord, MA, USA" ],
   "rows" : [
      {
         "elements" : [
            {
               "distance" : {
                  "text" : "1 m",
                  "value" : 0
               },
               "duration" : {
                  "text" : "1 min",
                  "value" : 0
               },
               "duration_in_traffic" : {
                  "text" : "1 min",
                  "value" : 0
               },
               "status" : "OK"
            },
            {
               "distance" : {
                  "text" : "10.9 km",
                  "value" : 10909
               },
               "duration" : {
                  "text" : "13 mins",
                  "value" : 804
               },
               "duration_in_traffic" : {
                  "text" : "13 mins",
                  "value" : 776
               },
               

In [23]:
import json

myDict = {
    "people": [
        {
            "name": "Bob",
            "age": 30,
            "weight": 100
            },
        {
            "name": "Daniel",
            "age": 45,
            "weight": 120
        }
    ]
}

jsonString = json.dumps(myDict)

jsonObject = json.loads(jsonString)

print(jsonObject["people"])

[{'name': 'Bob', 'age': 30, 'weight': 100}, {'name': 'Daniel', 'age': 45, 'weight': 120}]


In [33]:
url = f"https://maps.googleapis.com/maps/api/distancematrix/json?origins=Lexington+MA+USA|Concord+MA+USA&destinations=Lexington+MA+USA|Concord+MA+USA&departure_time=now&key={API_KEY}"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)


loadJson = json.loads(response.text)
print((loadJson)["rows"])
print((loadJson)["origin_addresses"])

[{'elements': [{'distance': {'text': '1 m', 'value': 0}, 'duration': {'text': '1 min', 'value': 0}, 'duration_in_traffic': {'text': '1 min', 'value': 0}, 'status': 'OK'}, {'distance': {'text': '10.9 km', 'value': 10909}, 'duration': {'text': '13 mins', 'value': 804}, 'duration_in_traffic': {'text': '12 mins', 'value': 741}, 'status': 'OK'}]}, {'elements': [{'distance': {'text': '10.7 km', 'value': 10652}, 'duration': {'text': '13 mins', 'value': 791}, 'duration_in_traffic': {'text': '12 mins', 'value': 734}, 'status': 'OK'}, {'distance': {'text': '1 m', 'value': 0}, 'duration': {'text': '1 min', 'value': 0}, 'duration_in_traffic': {'text': '1 min', 'value': 3}, 'status': 'OK'}]}]
['Lexington, MA, USA', 'Concord, MA, USA']


In [40]:
import numpy as np
origins = ['Lexington, MA, USA', 'Concord, MA, USA']
destinations = ['Lexington, MA, USA', 'Concord, MA, USA']
#zip the origin and destination into tuples to store in each structured npArray element, create row major arrangement of tuples then serialize into numpy structured array
travels = []
for loc in origins:
    for loc2 in destinations:
        travels.append((loc, loc2))
print(travels)

[('Lexington, MA, USA', 'Lexington, MA, USA'), ('Lexington, MA, USA', 'Concord, MA, USA'), ('Concord, MA, USA', 'Lexington, MA, USA'), ('Concord, MA, USA', 'Concord, MA, USA')]


In [48]:
import itertools
import numpy as np
origins = ['Lexington, MA, USA', 'Concord, MA, USA', 'Seattle']
destinations = ['Lexington, MA, USA', 'Concord, MA, USA']
travels = list(itertools.product(origins, destinations))
print(travels)
c = travels.reshape(len(origins), len(destinations), order = "F")

[('Lexington, MA, USA', 'Lexington, MA, USA'), ('Lexington, MA, USA', 'Concord, MA, USA'), ('Concord, MA, USA', 'Lexington, MA, USA'), ('Concord, MA, USA', 'Concord, MA, USA'), ('Seattle', 'Lexington, MA, USA'), ('Seattle', 'Concord, MA, USA')]


AttributeError: 'list' object has no attribute 'reshape'

In [25]:
import numpy as np
data = loadJson["rows"]
times = np.array()
print(len(data))
print(times)
for i, element in enumerate(data):
    print(element)
    print(i)
    for j, unit in enumerate(element["elements"]):
        print(j)
        duration = unit["duration"]
        print(duration)
        value = duration["value"]
        print(value)
        times[i][j] = tuple(value, i)
        print(times[int(i)][int(j)])
print(times)

#save the value as the time it takes for travel
#save i as the index so that a structured numpy array can be used to save routes

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
sample = np.array([
    [1, 3, 4],
    [4, 5, 6],
    [7, 8, 9,],
    [10, 11, 12]
])

def getRoute(matrix, route = None, loc = 0):
    if route is None:
        route = [min(matrix[loc])]
    getRoute(matrix, route, min())
    

[[ 1  3  4]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
